### ISSUE TITLE
关注中，建议使用支持markdown的编辑器

### ISSUE THREAD

**Issue by wellmoonloft** [Away0x/gin_bbs#1]

**Comment by wellmoonloft** [comment]
这个我选了好久，建议一下
另外现在这个版本是可用的状态吗？我正好想要部署一个。
https://github.com/Ionaru/easy-markdown-editor

**Comment by Away0x** [comment]
> 这个我选了好久，建议一下
> 另外请问现在这个版本是可用的状态吗？我正好想要部署一个。
> https://github.com/Ionaru/easy-markdown-editor

gin_bbs 是我学习 go 的一个玩具项目，没有仔细测试过。你可以 fork 然后自己添加一下 md 编辑器呢。
