### ISSUE TITLE
新跑起来的项目，分享 教程 问答 公告四个部分点击进去，会显示404页面。

### ISSUE THREAD

**Issue by JimmyLee05** [Away0x/gin_bbs#3]
从Git上下载源码，下载好依赖，配合好数据库相关。

最后Goland run项目，项目成功运行，打开http://localhost:8889/看到前端页面。

但新建的用户，在点击分享 教程 问答 公告选项时，会显示404页面

**Comment by Away0x** [comment]
> 从Git上下载源码，下载好依赖，配合好数据库相关。
> 
> 最后Goland run项目，项目成功运行，打开[http://localhost:8889/看到前端页面。](http://localhost:8889/%E7%9C%8B%E5%88%B0%E5%89%8D%E7%AB%AF%E9%A1%B5%E9%9D%A2%E3%80%82)
> 
> 但新建的用户，在点击分享 教程 问答 公告选项时，会显示404页面

这可能是因为没有分类的数据，新项目可以使用 make mock 命令生成这些数据
