### ISSUE TITLE
请问管理员是怎样注册的

### ISSUE THREAD

**Issue by JimmyLee05** [Away0x/gin_bbs#4]
先感谢作者的开源。

我遇到问题是应该有管理员这个角色，但没找到怎么弄。

一般会写在sql文件里，运行项目前往数据库里写，这个sql文件没看到。

新注册了用户，查看数据库 users这个字段，只有自己注册的这个用户。

**Comment by Away0x** [comment]
新项目可以运行 make mock 生成数据
管理员注册功能是放在管理员后台的(.....只不过我管理员后台还没写...)，不过已经写好了对应接口了 controllers/api/user

**Comment by Away0x** [comment]
> 先感谢作者的开源。
> 
> 我遇到问题是应该有管理员这个角色，但没找到怎么弄。
> 
> 一般会写在sql文件里，运行项目前往数据库里写，这个sql文件没看到。
> 
> 新注册了用户，查看数据库 users这个字段，只有自己注册的这个用户。

make mock 命令会生成一位站长角色用户和一位管理员角色用户，代码详见 database/factory/user，如果需要更多管理员可修改该处代码。可视化添加管理员的功能还没写

**Comment by JimmyLee05** [comment]
弄好了 谢谢 🤝

**Comment by JimmyLee05** [comment]
我把这个issue关掉了，有机会请你喝咖啡 /::D
